### ISSUE TITLE
Looking forward to get involved and contribute to the community 🎉

### ISSUE THREAD

**Issue by Kaushal-Kishore-Gupta** [BlackTimber-Labs/join-us#1]
### First Name

Kaushal

### Last Name

Kishore

### Discord Username (if applicable)

Knack

### Let us understand your motive.

Very high motive

**Comment by RITEKROUNAK** [comment]
Hey  @Kaushal-Kishore-Gupta 👋🏻

Thanks for requesting an invite! Welcome to BlackTimber Labs Community 🎉

Before going ahead, I would want you to complete the below To-Do list.

Your To-Do List ✔️
 
   - [ ] Accept the invitation sent to you via mail.
      
   - [ ] Change the appearance of this organization to "Public" from the people list here.
      
   - [ ] Join our WhatsApp Group [here](https://chat.whatsapp.com/CVrBjAtYqxs6d7GFqZmhrR).

Feel free to share your excitement on socials with #BlackTimberLabs.
Close this issue once you complete all the above points.
<hr>
Looking forward to interacting with you in our community! Welcome once again! 🤓
